name: check-codestyle
on:
  pull_request:

jobs:
  check-codestyle:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    name: check codestyle
    steps:
      - uses: actions/checkout@v2
      - name: check core codestyle 
        run: source ./apps/ci/ci-codestyle.sh
        
      - uses: wolletd/clang-format-checker@v1
        with:
          target-ref: master
      - name: check format
